# Generated by Django 4.2.27 on 2025-12-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rating_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
